host: https://trade-testing.casamiel.cn

base_username: test001
base_password: Augmn@123456

#db connection info of danta project
mysql_connection:
  host: 192.168.0.21
  user: dev_casamiel
  password: Vv7XaBvQagWIo7NB
  database: dev_casamiel_db
  port: 1433
#   host: