host:

base_username:
base_password:


skip_case_tags: not-ready|not-run

#db connection info of danta project
mysql_connection:
  host: 192.168.0.21
  user: dev_casamiel
  password:
  database: 
  port: 1433
